// File generated by Antigravity (manual reconstruction).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtWEl2pmE6ONGn-YBPc-w0caneZMPFZm0',
    appId: '1:62125287537:web:50e57adc824cfa966ed3d0',
    messagingSenderId: '62125287537',
    projectId: 'renosh-4569b',
    authDomain: 'renosh-4569b.firebaseapp.com',
    storageBucket: 'renosh-4569b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWEl2pmE6ONGn-YBPc-w0caneZMPFZm0',
    appId: '1:62125287537:android:b105c7db9024caaa6d34d3',
    messagingSenderId: '62125287537',
    projectId: 'renosh-4569b',
    storageBucket: 'renosh-4569b.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAtWEl2pmE6ONGn-YBPc-w0caneZMPFZm0',
    appId: '1:62125287537:web:50e57adc824cfa966ed3d0',
    messagingSenderId: '62125287537',
    projectId: 'renosh-4569b',
    authDomain: 'renosh-4569b.firebaseapp.com',
    storageBucket: 'renosh-4569b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtWEl2pmE6ONGn-YBPc-w0caneZMPFZm0',
    appId: '1:62125287537:web:40bf14bdff3b89336d34d3',
    messagingSenderId: '62125287537',
    projectId: 'renosh-4569b',
    authDomain: 'renosh-4569b.firebaseapp.com',
    storageBucket: 'renosh-4569b.firebasestorage.app',
  );
}
